### PR TITLE
using guava Preconditions in UpdateTopologyManager

### PR DESCRIPTION
**Pull request by mycFelix**
As #1612 mentioned, this PR is trying to use guava Preconditions in UpdateTopologyManager class for checking conditions and replace the `assertTrue` method. 

The key changes are following:

* add `com.google.common.base.Preconditions`
* remove `assertTrue` method
* use `Preconditions.checkArgument` or `Preconditions.checkState`

cc: @billonahill

### CODE REVIEW

**Comment by billonahill** [comment]
Changes look good, but can we not prefix "ERROR:" to every message string? These messages are going to be used as the message to a RuntimeException, which should be ultimately logged as SEVERE, so no need to also put ERROR in the message.

**Comment by mycFelix** [comment]
@billonahill Thanks for your suggestion and the PR was updated. BTW, any comment if we do the same change on ByteAmount class, is it necessary?

**Comment by billonahill** [comment]
👍 thanks!

Doing the same in `ByteAmount` would be great thanks.

**Comment by mycFelix** [comment]
@billonahill - I'll send another PR for `ByteAmount`

**Comment by objmagic** [comment]
👍

**Pull request merged**
