### PR TITLE
DO NOT MERGE Convert container id type to int from String

### LINKED ISSUE #1295: Should container's id be of type Integer?
Currently a container's `id` is of `String` type in `PackingPlan` https://github.com/twitter/heron/blob/master/heron/spi/src/java/com/twitter/heron/spi/packing/PackingPlan.java#L201. However it is assumed to be of type Integer in most places in the code. For e.g.

1. https://github.com/twitter/heron/blob/master/heron/packing/src/java/com/twitter/heron/packing/roundrobin/RoundRobinPacking.java#L363
1. https://github.com/twitter/heron/blob/master/heron/schedulers/src/java/com/twitter/heron/scheduler/local/LocalScheduler.java#L43
1. https://github.com/twitter/heron/blob/master/heron/proto/scheduler.proto#L29

As a result there is a lot of Integer-String conversion going around in the code base. IMO this clutter and unseen errors could be minimized if we accept container's Id to be an Integer. Thoughts?

### PR DESCRIPTION
**Pull request by ashvina**
Fixes #1295 
Container Id is declared as of type String. The value of id is always an int.
The users always assume id to be an int and the code is sprinkled with
int-to-string-to-int conversion. This update fixes it.

### CODE REVIEW

**Comment by billonahill** [comment]
👍 !!!

**Comment by objmagic** [comment]
👍

**Comment by kramasamy** [comment]
Nice one!

**Comment by objmagic** [comment]
Please fix failed unit test

**Comment by objmagic** [comment]
👍

**Comment by kramasamy** [comment]
@objmagic - do not merge this unless @ashvina says yes.

**Comment by objmagic** [comment]
oh sorry. Reverting...

**Comment by objmagic** [comment]
My bad. I should not merge this...

**Comment by objmagic** [comment]
sorry I didn't notice the "DO NOT MERGE". This is very inappropriate. Apology...

**Pull request merged**
