### PR TITLE
Added Streamparse copyrights to PyHeron API.

### LINKED ISSUE #1259: Streamparse copyright necessary for under heron/pyheron

### PR DESCRIPTION
**Pull request by taishi8117**
Resolves #1259 

Note that [`component_spec.py`](https://github.com/taishi8117/heron/blob/pyheron/copyright/heron/pyheron/src/python/component/component_spec.py) is original.

### CODE REVIEW

**Comment by billonahill** [comment]
Will this pass checkstyles?

**Comment by taishi8117** [comment]
@billonahill it seems to have passed. I think we don't have a Python check style for copyright strings, which we should probably do?

**Comment by billonahill** [comment]
👍 

(yes we should add a copywrite check for py)

**Comment by objmagic** [comment]
👍 

@kramasamy any final comment? I think license related PR needs your final review

**Comment by kramasamy** [comment]
👍

**Pull request merged**
