### PR TITLE
Joshfischer/eco config

### PR DESCRIPTION
**Pull request by joshfischer1108**
@kramasamy

This pull request contains the code to create Heron Topologies using ECO.  This would be considered a first pass to support defining topologies with Java based spouts and bolts.  The hope is that you can take any project that used Flux to create topologies and run them in Heron after following the steps here -> https://twitter.github.io/heron/docs/migrate-storm-to-heron/

An additional step is to include the eco-core in the Flux topology project as a dependency as well.  Imagine it would be something similar to the below in a Maven project:

```
<dependency>
        <groupId>com.twitter.heron</groupId>
        <artifactId>eco-core</artifactId>
        <version>0.0.97</version>
</dependency>

```
An example of how to submit an ECO topology would be as follows:
```
heron submit local ~/path/to/target/heron-example-jar-with-dependencies.jar \
 com.twitter.heron.eco.Eco \
  --eco-config-file /
~/path/to/yaml/simple_wordcount.yaml  
```

The "heron-example-jar-with-dependencies.jar" should contain all of the referenced spouts and bolts that are defined in the simple_wordcount.yaml file.

I will follow up with another pull request  soon to update the docs on the web on how to define ECO topology files, and what to expect with using ECO.

 Multi-lang functionality that Flux provided is still to be discussed. E.g., The flux shell wrappers 

```
<dependency>
        <groupId>org.apache.storm</groupId>
        <artifactId>flux-wrappers</artifactId>
        <version>${project.version}</version>
</dependency>
```

Do we want them pulled over to our project?  Would we like to rename them and so forth.

Also, since the verbose flag isn't considered an unknown argument it isn't passed on to the Eco.class to specify what level of logging to print.  As of now the only output from the ECO project should  be something similar to what Flux displayed while deploying the Storm topologies. Below is an example:

```
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: ---------- TOPOLOGY DETAILS ----------
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: Topology Name: sliding-window-topology
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: --------------- SPOUTS ---------------
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: spout-1 [1] (org.apache.storm.flux.examples.TestWordSpout)
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: ---------------- BOLTS ---------------
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: bolt-1 [1] (org.apache.storm.flux.examples.TestWindowBolt)
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: bolt-2 [1] (org.apache.storm.flux.examples.TestPrintBolt)
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: --------------- STREAMS ---------------
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: spout-1 --FIELDS--> bolt-1
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: bolt-1 --SHUFFLE--> bolt-2
Jan 07, 2018 4:09:47 PM com.twitter.heron.eco.Eco printTopologyInfo
INFO: -------------------------------------- 
```

It should also be noted that ECO topologies can only be assembled with spouts and bolts from Storm at this time.

I hope these details are sufficient enough.  Look forward to any thoughts or concerns.

### CODE REVIEW

**Comment by joshfischer1108** [comment]
I should also mention that most of the this code is based off the Apache Storm Flux implementation.  There has been some refactoring done, but still largely based off Storm's Flux.

**Comment by kramasamy** [comment]
@joshfischer1108 - thanks for the great contribution. I was wondering if you could add a few examples.

**Comment by joshfischer1108** [comment]
@kramasamy Will do.

**Comment by kramasamy** [comment]
@joshfischer1108 - PR looks good to me. Are there any additional commits that is coming along or ready to merge?

**Comment by joshfischer1108** [comment]
@kramasamy I think we should be good for a first pass.  I ran into some of the unknown issues last night while trying to move more examples from the Flux repo.  For instance, Heron's version of Storm does not include the package below
```
import org.apache.storm.state.*
```
So any of bolts or spouts that contain this, won't work.  I'm sure you are aware, just making sure to let it be known.   I have more examples I would like to create, but I will do them over the next few weeks.  Once this is merged, I will work on writing some docs in the static markdown files on how to run this examples and how to create your own ECO topologies.

If you are ok with this, then let's merge this branch.

**Comment by kramasamy** [comment]
@joshfischer1108 - state is implemented differently with Heron. After merging this branch, it will be great to add documentation on how to use it. It will be nice to translate into a blog as well. Thanks for the great contribution.

**Comment by joshfischer1108** [comment]
@kramasamy Will do!

**Pull request merged**
