### PR TITLE
Update website

### PR DESCRIPTION
**Pull request by lucperkins**
This includes the changes fixing the sidebar issue

### CODE REVIEW

**Comment by billonahill** [comment]
@lucperkins looks like this merge has conflicts. Could you pull from upstream and see how things look?

**Comment by lucperkins** [comment]
@billonahill To be honest, I had reservations about the pull request model for this and my doubts have been confirmed. I tried to merge with `upstream/gh-pages` here and that generated 100+ merge conflicts, which makes sense because there will *always* and by necessity be merge conflicts on this branch because we're dealing with generated content, not source content. It's not clear that merging makes sense to begin with because there's nothing to be gained by merging with files that are meant to be potentially obliterated when `make site` is run.

**Comment by billonahill** [comment]
@lucperkins if you're getting a merge conflict, I will too and we won't be able to commit. (I confirmed this)

I suspect the conflicts are because your remote has build date tags inserted into pages that conflict with the upstream remote. To resolve you can reset with the upstream remote and rebuild and you won't have conflicts.

Assuming `origin` is your fork and `upstream` is twitters:
```
$ cd workspace/heron
$ git pull upstream/master
$ cd website/public
$ git pull upstream/gh-pages
$ git reset upstream/gh-pages --hard
# push this to your gh-pages fork and verify your remote is in sync with the upstream
$ git status # should show everything clean
$ cd .. && make site && cd -
# commit to your fork again and you should have a clean diff for a PR. You might need to force push:
$ git push -f origin gh-pages
```

Now you can make a clean PR.

**Comment by lucperkins** [comment]
@billonahill Done. I can see now that I misunderstood your initial request. Makes perfect sense.

**Pull request closed without merging**
