### PR TITLE
replace the license for all files under storm directory

### PR DESCRIPTION
**Pull request by nlu90**
for files under storm directory, we respect the original storm license

### CODE REVIEW

**Comment by kramasamy** [comment]
@nlu90 - we need to fix the styling as well in order for the copyright to go through.

**Comment by billonahill** [comment]
👍 for the checkstyle change

**Comment by nlu90** [comment]
@kramasamy Can you have a look at this PR?

**Comment by kramasamy** [comment]
looks good - shit it!

**Pull request merged**
