### PR TITLE
Adding annotations to specify interface usage

### LINKED ISSUE #953: Annotation scheme for interfaces that are evolving, private, etc.
Hadoop has an annotation scheme to use to convey to users if public interfaces or methods are stable, unstable, evolving, public, or private. We should leverage something similar to make contracts clear.

https://hadoop.apache.org/docs/r2.7.2/api/org/apache/hadoop/classification/package-summary.html

### PR DESCRIPTION
**Pull request by billonahill**
Fixes #953.

Let me know what folks think of this approach and the classifications. Borrowed heavily from how Hadoop does things.

### CODE REVIEW

**Comment by kramasamy** [comment]
@billonahill - this is great. I was wondering if there is a way to discourage people using an API - like warnings etc. I see sometimes people are using directly the Heron API - which should be completely discouraged. If we can find a way to enforce, it will be great!

**Comment by billonahill** [comment]
@kramasamy yes we should be able to do things like check at compile time if a class not in `com.twitter.heron` is implementing a Private or Unstable interface and emit a warning.

I don't think we detect at runtime (or even compile time) if a class is calling a class that they shouldn't.

**Comment by billonahill** [comment]
Update: @kramasamy it seems annotations can't be inherited which means that if a class _extends a superclass_ that has a given annotation we can detect that at compile time and warn, but if a class _implements an interface_ that has a given annotation we can not detect that.

**Comment by kramasamy** [comment]
@billonahill - ok. I think it is better than the current state which is nothing.

**Comment by kramasamy** [comment]
👍

**Comment by billonahill** [comment]
@kramasamy I just added an annotations processor which will emit warnings at compile time if a non-heron class extends a class marked as Private, LimitedPrivate or Unsable. 
```
$ javac -cp "bazel-bin/heron/spi/src/java/libheron-spi.jar:bazel-bin/heron/api/src/java/libclassification.jar:bazel-bin/heron/proto/libproto_topology_java.jar" billg/*.java com/twitter/heron/*.java
billg/BillPacking.java:17: warning: billg.BillPacking extends from a class annotated with com.twitter.heron.classification.InterfaceStability.Unstable
public class BillPacking extends com.twitter.heron.NullPacking {
       ^
billg/BillPacking.java:17: warning: billg.BillPacking extends from a class annotated with com.twitter.heron.classification.InterfaceAudience.LimitedPrivate
public class BillPacking extends com.twitter.heron.NullPacking {
       ^
2 warnings
```

**Comment by kramasamy** [comment]
@billonahill - this is great!.

**Comment by kramasamy** [comment]
@billonahill - should we merge this?

**Comment by billonahill** [comment]
@kramasamy this is merged.

**Comment by kramasamy** [comment]
sorry - I did not see the change in status at the top :(

**Pull request merged**
