### PR TITLE
Delete a topology's PackingPlan when kill is invoked

### LINKED ISSUE #1347: Kill topology should delete packingPlan
A topology kill operation removes all topology files from state manager. However it is not deleting the topolgy's `PackingPlan`

```
$ ls -R .herondata/repository/state/local/
.herondata/repository/state/local//executionstate:
ExclamationTopology
.herondata/repository/state/local//packingplans:
ExclamationTopology
.herondata/repository/state/local//pplans:
ExclamationTopology
...
$ heron kill local ExclamationTopology
...
$ ls -R .herondata/repository/state/local/
.herondata/repository/state/local//executionstate:
.herondata/repository/state/local//packingplans:
ExclamationTopology
.herondata/repository/state/local//pplans:
.herondata/repository/state/local//schedulers:
...
```

`PackingPlan` was added in #1284.

### PR DESCRIPTION
**Pull request by ashvina**
Fixes #1347

### CODE REVIEW

**Comment by mycFelix** [comment]
Great!

**Comment by billonahill** [comment]
👍 

This change is included in #1334 fyi.

**Comment by kramasamy** [comment]
Should we merge this?

**Comment by billonahill** [comment]
Let's cancel this in favor of #1334 which should merge soon.

**Comment by kramasamy** [comment]
@ashvina - if this is not needed, please close this.

**Comment by billonahill** [comment]
This was addressed in #1334 so closing.

**Pull request closed without merging**
