### PR TITLE
Remove unused packing plan code

### PR DESCRIPTION
**Pull request by billonahill**

### CODE REVIEW

**Comment by objmagic** [comment]
do we need to change [FirstFitDecreasingPackingTest.java](https://github.com/twitter/heron/blob/691f19ddba080e84ee824acc30de893907ffa3f9/heron/packing/tests/java/com/twitter/heron/packing/binpacking/FirstFitDecreasingPackingTest.java#L109) accordingly?

**Comment by billonahill** [comment]
@objmagic no, there are no consumers of these methods. They're leftover from a previous refactor that used another approach.

**Comment by objmagic** [comment]
You are right I forgot to check if arguments match.

**Comment by objmagic** [comment]
👍

**Pull request merged**
