### PR TITLE
New code highlighting theme for the docs

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds a much better-looking code syntax highlighting theme for code blocks that, very importantly, involves no new build or installation steps.

These changes are purely aesthetic so feel free to de-prioritize if necessary.

### CODE REVIEW

**Comment by kramasamy** [comment]
@lucperkins - it will be nice if you could add a screenshot.

**Comment by lucperkins** [comment]
@kramasamy Here's an example:

screen shot 2016-05-27 at 7 16 39 am

**Comment by lucperkins** [comment]
@kramasamy Actually, I'd recommend visiting the site on my fork: http://lucperkins.github.io/heron/docs/getting-started/

**Comment by kramasamy** [comment]
looks good to me! @maosongfu @nlu90 @billonahill @objmagic @saileshmittal - any comments?

**Comment by objmagic** [comment]
looks beautiful! Thanks Luc

**Comment by billonahill** [comment]
@lucperkins looks like your site isn't showing the changed version anymore, but the formats above LGTM.

**Comment by lucperkins** [comment]
@billonahill Yeah, unfortunately my personal site is showing the changes in #835 at the moment.

**Pull request merged**
