### PR TITLE
Bump heron version in config to 0.14.0

### PR DESCRIPTION
**Pull request by objmagic**

### CODE REVIEW

**Comment by nlu90** [comment]
👍

**Comment by objmagic** [comment]
@kramasamy 

as for your concern in [this comment](https://github.com/twitter/heron/pull/815/files/f9ba523479345d807c5a02af84c19bee6743f748#r64969974), version number in ``config.yaml`` is hardcoded currently. As far as I know, YAML variables are set statically. Of course, one can write a script to generate a YAML file dynamically from template to set [``heron``](https://github.com/twitter/heron/pull/825/files#diff-a17fa31e069ba907a0e20ab17a007d74L23) to the output of ``git describe --tags --abbrev=0``

**Comment by objmagic** [comment]
This PR is better to be merged after #815

**Comment by objmagic** [comment]
cf #827

**Comment by objmagic** [comment]
close because of #827

**Pull request closed without merging**
