### PR TITLE
Add StreamMgr client and MetricsMgr client for python topology

### PR DESCRIPTION
**Pull request by taishi8117**
They are used to communicate with stream managers and metrics managers for Python heron instance.
Related PR: #1196 

Note that ``st_stmgr_client.py`` provides StreamMgr client for single-thread heron instance.

### CODE REVIEW

**Comment by kramasamy** [comment]
👍

**Comment by kramasamy** [comment]
@objmagic - do you have any comments on this?

**Comment by objmagic** [comment]
Other than some place which use string concatenation instead of formatter, this PR looks fine.

**Comment by kramasamy** [comment]
@taishi8117 - can you please take care of @objmagic feedback and we should be good to merge it.

**Comment by taishi8117** [comment]
@kramasamy They should have been fixed in https://github.com/twitter/heron/pull/1197/commits/4ab7e4f586e05cb8925e7c9cd2f00d8b005df11c and https://github.com/twitter/heron/pull/1197/commits/e0ecb77124984d9f5c908c8536a574c7c31a75f2.

**Pull request merged**
