### PR TITLE
force version and timestamp to be string

### PR DESCRIPTION
**Pull request by nlu90**
#920 

Tested locally:
```
Heron is now installed!

Make sure you have "/Users/nlu/bin" in your path.

See http://heronstreaming.io/docs/getting-started for how to use Heron.

heron.build.version : 'neng/fix-version-type'
heron.build.time : Tue Jun 14 21:10:18 PDT 2016
heron.build.timestamp : '1465963818000'
heron.build.host : tw-mbp-nlu
heron.build.user : nlu
heron.build.git.revision : e53c0cf173799dd7802ac3f3bb4e16fad8cdfa04
heron.build.git.status : Modified
```

### CODE REVIEW

**Comment by billonahill** [comment]
Why would we not want timestamp to be numeric?

**Comment by nlu90** [comment]
@billonahill In the `Context.java` code, the timestamp is fetched as follows:

```java
  public static String buildTimeStamp(Config cfg) {
    return cfg.getStringValue(ConfigKeys.get("BUILD_TIMESTAMP"));
  }
```

We either make it a string in yaml or fetch it as a long in the code. I'm fine with either solution, let me know your idea.

**Comment by billonahill** [comment]
Seems like it should always be a long to me.

**Comment by nlu90** [comment]
@billonahill Updated. Timestamp now is Long.

**Comment by billonahill** [comment]
👍

**Pull request merged**
