### PR TITLE
Add Spout Instance and Bolt Instance for Python topologies

### PR DESCRIPTION
**Pull request by taishi8117**
Instance part of #1196

### CODE REVIEW

**Comment by kramasamy** [comment]
👍

**Comment by objmagic** [comment]
👍

**Comment by objmagic** [comment]
Code looks good, but I will add unit tests for this PR.

**Comment by kramasamy** [comment]
@objmagic - is this ready to be merged?

**Comment by objmagic** [comment]
Yes. But I'm sorry that unit tests are hard to write and I'm not in good health condition now. I may add some later. Integration test which Taishi now is writing could be helpful though.

Anyway, I'd day we can merge this PR.

**Comment by kramasamy** [comment]
Ok - sounds good. I will merge it tomorrow.

**Pull request merged**
