### PR TITLE
Refactor usage of PhysicalPlanHelper, dedup simulator code

### PR DESCRIPTION
**Pull request by billonahill**
No new functionality here, refactoring how `PhysicalPlanHelper` is used by `SpoutInstance` and `BoltInstnance` to make it easier to update the `TopologyContext`, which is required for #1509. I encountered a lot of duplicate code between the instance classes and the simulator classes so I removed much of that as well.

### CODE REVIEW

**Comment by kramasamy** [comment]
Looks good to me! @maosongfu - can you take a look at the instance changes? @nlu90 - can you take a look at the simulator code?

**Comment by objmagic** [comment]
LGTM 👍

**Comment by billonahill** [comment]
Next I've got some more structural changes to make around the interaction between and  PhysicalPlanHelper/TopologyContextImpl but I'll break those into another review.

**Comment by billonahill** [comment]
Sorry for all the commits on this one but I realized I can simplify the approach. I've reverted some edits and am setting us up to allow `IInstance` to take an `update(PhysicalPlanHelper)` method since this is a core (i.e., internal only) class. The user bolts/spouts would then implement `UpdatableInstnace` which takes an `update(TopologyContext)` method.

**Comment by kramasamy** [comment]
New changes look good to me. 👍

**Pull request merged**
