### PR TITLE
Improve err msg of heron-explorer.

### LINKED ISSUE #1154: Improve error message when no topology is running under a cluster
change to "No topologies found"

### PR DESCRIPTION
**Pull request by objmagic**
resolves #1154

### CODE REVIEW

**Comment by objmagic** [comment]
@kramasamy

**Comment by kramasamy** [comment]
It should be  "No topologies in cluster"

**Comment by objmagic** [comment]
Right. Will fix. 

Kindly,

Runhang

**Comment by objmagic** [comment]
@kramasamy fixed

**Comment by kramasamy** [comment]
Look good. Ship it!

**Pull request merged**
