### PR TITLE
Use bufferevent to do Network I/O

### PR DESCRIPTION
**Pull request by srkukarni**
libevent has buffer event library that takes care of actually reading/writing from socket descriptors. Managing write readiness, reading/writing using vectors efficiently, zero copy buffer management are all done internally by bufferevent.
In this pr, we start using bufferevent to do the io rather than doing native i/o. This change greatly simplifies the networking code. There should be no performance penalty.
In addition to simplification of the code, this change has several benefits
1. bufferevents allow sophisticated rate limiting techniques(like leaky buckets) to control the rate of io.
2. bufferevents have priority groups which would in the future allow us to do differentiated io for spouts/bolts
3. adding ssl support for end to end encryption becomes trivial since bufferevents supports it natively.
4. Makes running stmgr on non posix api machines straightforward(windows)

### CODE REVIEW

**Comment by maosongfu** [comment]
@srkukarni This is a huge change. 

@nlu90 Could we plan a time and try this branch within the distributed env to see whether this pull request will work fine?

**Comment by srkukarni** [comment]
@maosongfu sounds like a plan!

**Comment by nlu90** [comment]
Here are the performace metrics comparison with Exclamation topology:

For CPU usage:


For Spout NextTuple Count:


For Bolt Execute Count:

**Comment by huijunw** [comment]
cool performance result @nlu90

**Comment by srkukarni** [comment]
@nlu90 Thanks for the graphs!
Do we have longer duration graphs(like day long or weekend long)?

**Comment by kramasamy** [comment]
@nlu90 - nice graphs.

**Comment by nlu90** [comment]
@srkukarni Yeah, here's the longer time: 3 day result

For CPU usage:
pasted image at 2017_09_11 05_29 pm

For Spout emit count:
pasted image at 2017_09_11 05_29 pm 1

For Bolt execute count:
pasted image at 2017_09_11 05_31 pm

**Comment by nlu90** [comment]
Some more metrics with some more fixes in the `sanjeevk/moveto_bufferevent` branch:

CPU:
pasted image at 2017_09_12 10_22 am


Spout Emit Count:
pasted image at 2017_09_12 10_22 am 1


Bolt Execute Count:
pasted image at 2017_09_12 10_23 am

And I also investigated that the CPUs are different for the two topologies' containers. The 0.15.2 release topology is running with better and faster CPUs compared to those used by bufferevent release topology.

**Comment by nlu90** [comment]
Further more experiment shows that given same cpus, the bufferevent version topology has better performance and is more stable than the current release. So this change is good to be merged now.

CPU usage:
screen shot 2017-09-14 at 12 08 32 pm

Spout Emit Count:
screen shot 2017-09-14 at 12 01 21 pm

Bolt Execute Count:
screen shot 2017-09-14 at 12 07 38 pm

**Pull request merged**
