### PR TITLE
Made custom grouping object for protobuf more generic

### PR DESCRIPTION
**Pull request by taishi8117**
Modified InputStream message in topology.proto, so that it is more extensible for multi-lang support.

Related PR: #1179, #1180

### CODE REVIEW

**Comment by objmagic** [comment]
I suggest we make the following change instead. Either both ``custom_grouping_object`` and ``CustomGroupingObjectType`` appear or neither exists.

````protobuf
message CustomGroupingObject {
    required byte custom_grouping_object = 1;
    required CustomGroupingObjectType type = 2;
}
...
{
   ...
   optional CustomGroupingObject obj = 5;
}
````
However, if this change breaks backward compatibility a lot, your change is fine.

**Comment by taishi8117** [comment]
@objmagic I considered that but to be safe with the backward compatibility, changing a type for the existing field id (5) might not be a good idea.

**Comment by objmagic** [comment]
@taishi8117 then it's fine. Let's wait other people's opinion though.

**Comment by billonahill** [comment]
@objmagic your suggestion is the right one IMO, but since it would break backward compatibility we have to compromise a bit with the proposed solution.

👍

**Comment by kramasamy** [comment]
I think it is ok to break backward compatibility - since a bunch of changes have been there for proto and further additions are coming as well.

**Comment by objmagic** [comment]
btw, it would be good to add some comments like "if you change this protobuf file, you need to make change accordingly for foo.py, bar.java, wee.cpp"

**Comment by billonahill** [comment]
@kramasamy I was also wondering about that. Internally we don't have any production jobs on OSS heron, by the looks of the task tracker. If we can break backward compatability we could do the right thing. @taishi8117 do you want to work on a patch to refactor our proto classes to use the pattern that @objmagic showed above?

**Comment by taishi8117** [comment]
@billonahill Yes, I will work on the patch to refactor them today.

**Comment by kramasamy** [comment]
I think this is a good time to change - if needed, so that we can minimize incompatible migrations.

**Comment by kramasamy** [comment]
Ship it 👍

**Comment by taishi8117** [comment]
We decided to leave this PR backward compatible for now, and we can later refactor them when we move to protobuf v3.0 and might need to break the backward compatibility anyways (#1183).

**Pull request merged**
