### PR TITLE
0.14.2 website build

### PR DESCRIPTION
**Pull request by lucperkins**
cc @kramasamy

Live version of these changes: http://lucperkins.github.io/heron

### CODE REVIEW

**Comment by objmagic** [comment]
I made some small changes on website. Can we hold this PR for a little while?

**Comment by objmagic** [comment]
@lucperkins I just merged in #1226. Can you build the website again?

**Comment by lucperkins** [comment]
@objmagic That most recent commit is a new build that takes your changes into account.

**Comment by objmagic** [comment]
👍

**Pull request merged**
