### PR TITLE
Add accordion-style sidebar

### PR DESCRIPTION
**Pull request by lucperkins**
Here's a screenshot:

screen shot 2016-05-27 at 4 14 53 pm

This is an accordion-style interface with some JS that "remembers" which tab is currently open.

### CODE REVIEW

**Comment by kramasamy** [comment]
This is nice - ship it!

**Comment by objmagic** [comment]
I cannot click the sidebar. I'm not sure if this is the same for others: https://objmagic.ml/heron/docs/getting-started/

**Comment by lucperkins** [comment]
@objmagic @kramasamy I found the issue. The accordion relies on jQuery and the jQuery URL currently being used (`http://code.jquery.com/jquery-2.2.1.min.js`) is HTTP rather than HTTPS, and so GitHub pages is refusing to fetch that resource. That URL also works via HTTPS so I'll submit a PR to change that.

**Comment by lucperkins** [comment]
@objmagic @kramasamy See PR #828

**Pull request merged**
