### PR TITLE
adding additional unit and integration tests for heron windowing support

### PR DESCRIPTION
**Pull request by jerrypeng**
Also added some null checks in client side

### CODE REVIEW

**Comment by jerrypeng** [comment]
@srkukarni @kramasamy Can you look.  Thanks!

**Comment by jerrypeng** [comment]
Test failed due to being too long.  Though all the java tests passed

**Comment by srkukarni** [comment]
@maosongfu is there a way to increase the ci timeout?

**Comment by maosongfu** [comment]
@srkukarni @jerrypeng Already requested and the timeout was increased: now it is 150mins. Let me know if it does not work.

**Comment by jerrypeng** [comment]
@maosongfu thank you!

**Comment by srkukarni** [comment]
Thanks @maosongfu That worked.

**Pull request merged**
