### PR TITLE
Change checkstyles to happen once before build on all files

### LINKED ISSUE #799: Shorten the travis-ci building time
A job taking longer than 50 minutes on travis-ci.org will be terminated like this:
The job exceeded the maximum time limit for jobs, and has been terminated.

Currently, heron travis-ci job runs: building, unit testing, style checking and integration tests, serially. And it is very likely the job exceeds 50mins.

### PR DESCRIPTION
**Pull request by billonahill**
Partially fixes #799 by not doing checkstyle on every compile.

### CODE REVIEW

**Comment by billonahill** [comment]
This patch is not yet ready to be merged. It needs more testing, since no all files are being checked it seems.

**Comment by billonahill** [comment]
This review changes CI to audit all java files at once. The java checkstyle takes 7 seconds, but the build still take 42 minutes.

**Comment by nlu90** [comment]
@billonahill I looked into the log, the local integration test takes 5 minutes, the integration test takes around 7 minutes, the unit test takes about 4 minutes.

I'm wondering if it's because of the ci waited for a long time to be executed.

**Comment by billonahill** [comment]
Yes, this change makes not much of a difference. I think the java checkstyles are a red herring. They seem like the cause of slownedd because they log every time a compile happens, but the don't actually take much time. Here's the timing summary with the checkstyles moved out:

```
Task duration summary for scripts/travis/ci.sh
===================================================
make site	0:02:02
scripts/travis/build.sh	0:25:58
scripts/travis/test.sh	0:12:48
```

I'm included to cancel this pull request.

**Comment by kramasamy** [comment]
@billonahill - since java checkstyles do not take time, are we close this pull request?

**Pull request closed without merging**
