### PR TITLE
Add flags to the heron executor.

### PR DESCRIPTION
**Pull request by cckellogg**
Add executor flags to variables so they no longer have to have an order. Also, this makes it easier to debug and reason about the values. 

This cleans up the previous pull request https://github.com/twitter/heron/pull/240

### CODE REVIEW

**Comment by kramasamy** [comment]
@objmagic @huijunw - any comments?

**Comment by huijunw** [comment]
our ci is dead. @objmagic is trying to fix it. we plan to test this pr after we fix the ci.

**Comment by huijunw** [comment]
our ci pass

**Comment by objmagic** [comment]
sorry i broke this branch when resolving the conflict... will try to restore it.

**Pull request merged**
