### PR TITLE
Upgrade Pex to 1.1.11.

### LINKED ISSUE #1051: Upgrade pex
Travis CI sometimes [fails](https://travis-ci.org/twitter/heron/builds/141222115) with the following error message related to Pex.

````
....
fastbuild/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/resolver.py", line 254, in build
    os.rename(target + '~', target)
OSError: [Errno 2] No such file or directory
____(06-30 00:08:42.656) Building complete.
____(06-30 00:08:42.664) Elapsed time: 530.480s, Critical Path: 517.13s
````

It seems that [this PR of Pex](https://github.com/pantsbuild/pex/pull/271#issue-157100630) fixed the problem. I suggest we should upgrade Pex.

### PR DESCRIPTION
**Pull request by objmagic**
resolves #1051

In this PR, I will restart CI many times to see if the same error will happen again...

### CODE REVIEW

**Comment by billonahill** [comment]
Looks good, thanks for doing this. Would you also please verify this branch in twitter's internal CI.

**Comment by kramasamy** [comment]
@objmagic - can you check with our internal version as @billonahill pointed out so that we can merge this?

**Comment by objmagic** [comment]
Internal CI passed @billonahill @kramasamy

**Comment by billonahill** [comment]
👍

**Comment by kramasamy** [comment]
@objmagic and @nlu90 - can this PR be merged if internal CIs work?

**Comment by objmagic** [comment]
@kramasamy yes

**Comment by billonahill** [comment]
One more think to check is to make sure the docker builds work. Once that's verified I think it's fine to merge.

**Comment by objmagic** [comment]
@kramasamy @billonahill 

Internal CI passed. I can also build and run on Docker following steps [here](https://github.com/twitter/heron/tree/master/docker).

I'll go ahead to merge it if everyone thing it's fine.

**Comment by nlu90** [comment]
👍  for internal jenkins CI

**Comment by objmagic** [comment]
@benley do you want to have a look at this PR?

**Comment by billonahill** [comment]
👍

**Comment by benley** [comment]
I think you might be missing some updates to pex/bin/pex.py; here's what that diff looks like from my repo: https://github.com/benley/bazel_rules_pex/pull/6/files#diff-da6b827279fc47e8b1603fe3af0f4a0e

The changes are pretty minor, so maybe you deliberately didn't include them?

**Comment by benley** [comment]
Aside from that, 👍

**Comment by objmagic** [comment]
@benley I applied your patch: https://github.com/twitter/heron/pull/1052/commits/37f9d7498c535dc13c0fec5e8b3c19c494ea1ce6

**Comment by objmagic** [comment]
Travis CI, internal CI, Docker build all passed, again.

**Pull request merged**
