### PR TITLE
Java unit test name changes in BUILD files

### PR DESCRIPTION
**Pull request by taishi8117**
- Changed Java unit test names in BUILD files, for compatibility with later versions of Bazel.
- This is needed for moving to bazel 0.2.3

### CODE REVIEW

**Comment by kramasamy** [comment]
👍

**Comment by billonahill** [comment]
Is this because newer bazel not allow `_`? The rest of the targets in the repo seem to use a lowercased-dash-delimited convention instead of CamelCase. Could we also follow that here?

**Comment by taishi8117** [comment]
@billonahill This is because the newer versions of Bazel require that for `java_test` fields, `name` needs to match with Java class name that is tested.
This PR should not conflict with the current master (built with bazel 0.1.2), and we are working on other necessary changes that might conflict with the current master in #869

**Comment by billonahill** [comment]
👍 

(not so sure how I feel about bazel's design decision there :) )

**Pull request merged**
