### PR TITLE
Make bazel updates for 6.0

### PR DESCRIPTION
**Pull request by aahmed-se**
This maintains backward compatibility with 0.54

### CODE REVIEW

**Comment by huijunw** [comment]
I have a question, what is our policy to update bazel version? Do we follow bazel version closely for each version?

**Comment by srkukarni** [comment]
@huijunw Its ok to introduce non breaking changes. i.e. there is a officially supported version(currently 0.5.4). As long as things work in that officially supported version, making any new changes to support newer version should be ok.
What do you think?

**Comment by huijunw** [comment]
@srkukarni thank you for the clarification.
needs @nlu90 comment

**Comment by nlu90** [comment]
@huijunw I suggest 1). we make sure things are not broken with any such dev tool upgrades; 2).  with the first point guaranteed, we move as fast as we can to help the oss community.

**Comment by kramasamy** [comment]
@nlu90 @huijunw - these changes are backward compatible withh bazel 0.5.4 and also works with bazel 0.6.0 as well.

**Pull request merged**
