### PR TITLE
Fix code block rendering.

### LINKED ISSUE #1283: First Fit Decreasing Packing Algorithm docs broken
The example code snippet at the bottom of this page is not rendering.

http://twitter.github.io/heron/docs/developers/packing/ffdpacking/

### PR DESCRIPTION
**Pull request by objmagic**
fix #1283 

(Atom editor automatically removes trailing white spaces so one only needs to review the last part)

cc @billonahill

### CODE REVIEW

**Comment by billonahill** [comment]
Why 4 backticks and not 3 as seen elsewhere in the md docs?

**Comment by objmagic** [comment]
ah, I am just used to using four backticks... will change to three now.

**Comment by billonahill** [comment]
So the issue was the wrong number of indent spaces?

👍

**Comment by objmagic** [comment]
@billonahill no. It is because a new line was not inserted before the code block.

**Pull request merged**
