### PR TITLE
Fix org/apache/storm/clojure/lang/Atom.java's package name

### PR DESCRIPTION
**Pull request by windie**

### CODE REVIEW

**Comment by maosongfu** [comment]
@nlu90 Can u take a look at this?

**Comment by kramasamy** [comment]
@windie - Is this for Storm 1.0.0+?

**Comment by windie** [comment]
@kramasamy - I just found the package name doesn't match the file path. However, I don't understand the hack here. @nlu90 could you take a look since you added this file?

**Comment by nlu90** [comment]
👍  

@windie This seems a typo when we added the new package namespace for storm compatibility

**Pull request merged**
