### PR TITLE
Do not spawn a process for basic system information

### PR DESCRIPTION
**Pull request by insomniacslk**

### CODE REVIEW

**Comment by billonahill** [comment]
Looks good @insomniacslk, thanks for the patch!

Would you please accept the CLA linked to from http://twitter.github.io/heron/docs/contributors/community/.

**Comment by insomniacslk** [comment]
@billonahill just accepted the CLA

**Comment by insomniacslk** [comment]
and also removed a line that I forgot around

**Comment by billonahill** [comment]
Great, this is so much cleaner. Thanks @insomniacslk.

**Pull request merged**
