### PR TITLE
check if the treemap is empty during metircscache purge process

### PR DESCRIPTION
**Pull request by huijunw**
check if the treemap is empty during purge process

### CODE REVIEW

**Comment by huijunwu** [comment]
if (!cacheMetric.isEmpty()) {
   for ( ;; /*this may throw exception*/ ) {
      // remove changes map
   }
}
i do not think puting the `for `loop inside `if `block can handle the exception throw from `for `loop.
the loop changes the collection and the exception may be thrown from inside `if `block.

**Comment by billonahill** [comment]
Can you clarify the excepton and what causes it? It's not clear from your description, so based on the code I assumed it was caused when calling ```cacheMetric.firstKey()``` when ```cacheMetric.isEmpty() == true```. Putting that check outside the for loop would keep that from happening no?

**Comment by huijunw** [comment]
The `for` loop changes the treemap. After entering the `if` block, the treemap may change to empty.

**Comment by billonahill** [comment]
Could we do this then instead? I'm suggesting for readability. Trying to decipher the reasoning for the null checks make the code harder to understand.
```
while (!cacheMetric.isEmpty()) {
  Long firstKey = cacheMetric.firstKey()
  if (firstKey < now - maxIntervalMilliSecs) {
    break;
  }
  cacheMetric.remove(firstKey);
}
```

**Comment by huijunw** [comment]
updated

**Pull request merged**
