### PR TITLE
Move taskId/componentIndex management into PackingPlanBuilder

### LINKED ISSUE #1579: Packing algorithms don't check for componentId collisions
The repacking algorithms (i.e., `FirstFitDecreasingPacking` and `ResourceCompliantRRPacking`) assert that the global task ids are unique, but they don't check that the `componentIndex` is unique to all components of a given type. As a result we currently have collisions when scaling.

The fix is to make it so that the packing algorithms don't even need to manage this. This logic can be entirely managed in the `PackingPlanBuilder` and the algos can just add/remove instances by `componentName` instead of by `InstanceId`.

### PR DESCRIPTION
**Pull request by billonahill**
Fixes #1579.

The current repacking algos can cause collisions with `componentIndex`. This patch fixes that by moving managment of `taskId` and `compoenentIndex` into `PackingPlanBuilder` since the packing algos shouldn't need to handle these.

This has the added benefit of simplifying the `PackingPlanBuilder` API, since add/remove calls can work just with `componentNames`, instead of `InstanceIds`.

### CODE REVIEW

**Comment by billonahill** [comment]
Any comments on this?

**Comment by billonahill** [comment]
@avflor @ashvina please review when you can.

**Comment by avflor** [comment]
@billonahill This LGTM.

**Comment by billonahill** [comment]
thanks @avflor for reviewing.

**Pull request merged**
