### PR TITLE
Website build with PyHeron related stuff

### PR DESCRIPTION
**Pull request by objmagic**
cc @lucperkins @billonahill @taishi8117 

You can view at http://objmagic.github.io/heron

### CODE REVIEW

**Comment by billonahill** [comment]
Reviewing this request by examining diffs is pretty hard. Could you publish the site to your fork and include a link so @taishi8117 and @lucperkins can review the changes that they expect to see on the site.

**Comment by lucperkins** [comment]
@objmagic Could you explain what the purpose of this PR is? Is this simply a new site build PR (as we've done in the past) or have you changed the underlying source as well?

**Comment by objmagic** [comment]
No. Just a build

**Comment by objmagic** [comment]
yeah, so if you use HTTPS (https://twitter.github.io/heron/), navbar on the left is dead...

**Comment by lucperkins** [comment]
@objmagic I'm not sure why that would be, but is that an issue? The heronstreaming.io URL resolves to HTTP.

**Comment by objmagic** [comment]
yeah, not a big deal. But my domain (objmagic.github.io) enforces HTTPS so people cannot navigate on my GitHub Heron page.

**Comment by lucperkins** [comment]
@objmagic Oh, okay, I see what you mean now. Perhaps it would be best if I were to submit a new build PR instead. Would you be opposed to that?

**Comment by billonahill** [comment]
IIRC we've seen that before when some includes had http:// in them. I don't recall the exact specifics though.

**Comment by objmagic** [comment]
@lucperkins @billonahill no worry. I will submit a new PR and fix this...

**Comment by objmagic** [comment]
site rebuilt with HTTPS JQuery. 

You can view at [objmagic.ml/heron](https://objmagic.ml/heron).

PyHeron related page is [here](https://objmagic.ml/heron/docs/developers/python/topologies/).

**Comment by objmagic** [comment]
will update this PR when #1266 is merged.

**Comment by objmagic** [comment]
This PR is good to go.

**Comment by taishi8117** [comment]
👍

**Pull request merged**
