### PR TITLE
fix centos5 BUILD file

### PR DESCRIPTION
**Pull request by nlu90**
The BUILD file for centos5 also needs to be updated according to the changes made in #939 to supress the unzip warnings

### CODE REVIEW

**Comment by billonahill** [comment]
👍 

@nlu90 or @kramasamy why do we have a separate BUILD process for centos5 than those in `scripts/packages`?

**Comment by nlu90** [comment]
@billonahill There are some platform-dependent bahavior during the build. I tried to use `scripts/package/BUILD` for centos building and encountered the following error

```
bazel build --config=centos scripts/packages:heron-client-install.sh
WARNING: Output base '/home/nlu/.cache/bazel/_bazel_nlu/3f912366ea080f2f98e424559c0207ed' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Found 1 target...
ERROR: /home/nlu/heron/scripts/packages/BUILD:100:1: null failed: build_tar failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar '--flagfile=bazel-out/local-fastbuild/bin/scripts/packages/heron-core-lib-instance.args': com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
  File "/home/nlu/.cache/bazel/_bazel_nlu/3f912366ea080f2f98e424559c0207ed/heron/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/__main__/../bazel_tools/tools/build_defs/pkg/build_tar.py", line 92
    mode = 0o755 if os.access(f, os.X_OK) else 0o644
               ^
SyntaxError: invalid syntax
Target //scripts/packages:heron-client-install.sh failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.326s, Critical Path: 0.66s
```

**Comment by billonahill** [comment]
I'm not sure what that is (maybe --verbose_failures would help) but ideally we could have a single build and use bazel to abstract out the OS specific stuff. That would be cleaner than copied & edited BUILD files.

**Comment by nlu90** [comment]
@billonahill Here's the output with `--verbose_failures` option

```
bazel build --config=centos scripts/packages:heron-client-install.sh --verbose_failures
WARNING: Output base '/home/nlu/.cache/bazel/_bazel_nlu/3f912366ea080f2f98e424559c0207ed' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Found 1 target...
ERROR: /home/nlu/heron/scripts/packages/BUILD:192:1: null failed: build_tar failed: error executing command 
  (cd /home/nlu/.cache/bazel/_bazel_nlu/3f912366ea080f2f98e424559c0207ed/heron && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar '--flagfile=bazel-out/local-fastbuild/bin/scripts/packages/heron-client-conf-aurora.args'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
  File "/home/nlu/.cache/bazel/_bazel_nlu/3f912366ea080f2f98e424559c0207ed/heron/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/__main__/../bazel_tools/tools/build_defs/pkg/build_tar.py", line 92
    mode = 0o755 if os.access(f, os.X_OK) else 0o644
               ^
SyntaxError: invalid syntax
Target //scripts/packages:heron-client-install.sh failed to build
INFO: Elapsed time: 2.542s, Critical Path: 0.16s
```

+1 for single BUILD file if possible.

**Pull request merged**
