### PR TITLE
Change AuroraController.appendAuroraCommandOptions to private

### PR DESCRIPTION
**Pull request by billonahill**
This method is not used outside of this class. Changing to private.

### CODE REVIEW

**Comment by maosongfu** [comment]
Should we change it into protected so later we can use it in Unit test?

**Comment by billonahill** [comment]
I prefer making methods as closed-scoped as possible and opening scope when needed. So once we write a test we can change it to protected and annotate it `@VisibleForTesting`.

**Comment by kramasamy** [comment]
👍

**Comment by maosongfu** [comment]
:+1:

**Pull request merged**
