### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by tobecontinued**
In HeronClient.java, 'Servers' should change to 'Clients'.

### CODE REVIEW

**Comment by maosongfu** [comment]
thanks for the contribution @tobecontinued - since this is the first time, you are sending a PR, can you please sign the CLA agreement?

https://engineering.twitter.com/opensource/cla

**Comment by kramasamy** [comment]
👍

**Comment by tobecontinued** [comment]
@maosongfu , It's not my first time send PR, Should I sign CLA again?

**Comment by kramasamy** [comment]
@tobecontinued - you have signed CLA before.

**Comment by maosongfu** [comment]
@tobecontinued Sorry you don't need to sign it again.

**Pull request merged**
