### PR TITLE
Added a topology status to the list all topologies ui.

### PR DESCRIPTION
**Pull request by cckellogg**
topologies-with-status

### CODE REVIEW

**Comment by billonahill** [comment]
While we're at it, could we also make it clear what the red font indicates?
Currently that's a bit of a mystery.

**Comment by cckellogg** [comment]
Can we address the font colors in another patch? This was preexisting code and I'm not sure what it means either. Here the code for the colors (https://github.com/twitter/heron/blob/master/heron/tools/ui/resources/static/js/alltopologies.js) lines 20 - 31.

**Comment by kramasamy** [comment]
@cckellogg - let us do another patch to appropriately report the status of the topologies in red

**Comment by kramasamy** [comment]
@billonahill - the proposal is to change the color from RED to normal and display the state as 'ORPHANED'. @cckellogg is doing it in a different PR. Any suggestions for this state other than 'ORPHANED'?

**Comment by billonahill** [comment]
@kramasamy the states we currently show align with the documented Heron states that users control via the Heron cli. Since 'ORPHANED' is not one of those, my concern is that it's meaning would also not be understood by a typical user. Somehow we need to convey exactly what is meant by orphaned or red-font. I'm open for UI suggestions for how to do that though, but I think it might need more of an explanation somewhere on the page.

**Pull request merged**
