### PR TITLE
We need to unregister the metric and delete it before clearing the map

### PR DESCRIPTION
**Pull request by srkukarni**

### CODE REVIEW

**Comment by congwang** [comment]
Looks good.

**Comment by nlu90** [comment]
👍

**Comment by maosongfu** [comment]
Looks good. I noticed that, during HandleConnectionClose(..), the instance_metric will not be cleaned (removed); will it be a problem too?

We need to verify the changes before merging it.

**Comment by maosongfu** [comment]
It does not solve the issue. WILL NOT MERGE this pull request.

**Comment by srkukarni** [comment]
@maosongfu Regardless of whether it fixes the bug that we saw, this itself is a memory leak that needs to be fixed.

**Comment by maosongfu** [comment]
Close this pull request due to #1801

**Pull request closed without merging**
