### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by objmagic**

### CODE REVIEW

**Comment by kramasamy** [comment]
👍

**Comment by billonahill** [comment]
👍 assuming you've verified that the site can still be properly built on mac and internal/external CI and that the rendering is correct.

**Comment by objmagic** [comment]
this seems to be the root cause: https://github.com/jakubpawlowicz/clean-css/issues/888

**Comment by huijunw** [comment]
👍

**Comment by objmagic** [comment]
CI is still using `node -v v0.10.36`. We need 0.12.x

**Pull request merged**
