### PR TITLE
Prepare default handler for all use cases.

### PR DESCRIPTION
**Pull request by objmagic**
since some users complained they see error like "No handler found..."

@taishi8117 can you have a quick look?

### CODE REVIEW

**Comment by kramasamy** [comment]
@objmagic - can you please comment why this is needed?

**Comment by objmagic** [comment]
it is possible that user simply imports the `Log` object without calling function ``configure``. This may cause exception "No handler found". So we at top level add a `logging.basic_config()` to prepare a default handler so that `Log` will always be properly initialized.

**Comment by kramasamy** [comment]
please add this comment in the code.

**Comment by kramasamy** [comment]
👍

**Pull request closed without merging**
