### PR TITLE
Add Kinesis spout to Heron.

### PR DESCRIPTION
**Pull request by reconditesea**
Port from Storm Kinesis spout with several updates and necessary changes to be compatible in Heron.

### CODE REVIEW

**Comment by kramasamy** [comment]
thanks for the contribution @reconditesea - since this is the first time, you are sending a PR, can you please sign the CLA agreement?

https://engineering.twitter.com/opensource/cla

**Comment by reconditesea** [comment]
@kramasamy Sure thing, done.

**Comment by nlu90** [comment]
Just a reminder, the license here is not the Apache License. It will fail checkstyle if the bazel BUILD file is added and travis conducts the integration test check.

**Comment by reconditesea** [comment]
@nlu90 Is it an option to update checkstyle to also accept Amazon License?

**Comment by nlu90** [comment]
@reconditesea Yeah,  it's possible to do that.

**Comment by kramasamy** [comment]
@reconditesea - any reason why closed this?

**Pull request closed without merging**
