### PR TITLE
Fix typo: 'filered' → 'filtered'.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by lucperkins** [comment]
+1

**Comment by objmagic** [comment]
+1

**Comment by kramasamy** [comment]
thanks for the fix @frewsxcv - can you please fill up the CLA agreement at

http://twitter.github.io/heron/docs/contributors/community/

for submitting the patch.

**Comment by frewsxcv** [comment]
> can you please fill up the CLA agreement at

Done

**Pull request merged**
