### PR TITLE
Fix a resource leak in MetricsSinksConfig

### PR DESCRIPTION
**Pull request by windie**

### CODE REVIEW

**Comment by maosongfu** [comment]
looks good to me. :+1:

**Comment by kramasamy** [comment]
@windie - one of the unit tests seems to have failed. Can you run the unit tests in your machine and see if everything passes? To run unit tests, do the following

```
bazel test --config=darwin heron/...
```

**Comment by windie** [comment]
@kramasamy - Passed locally: `Executed 114 out of 114 tests: 114 tests pass.` Seems `//heron/instance/tests/java:SpoutInstanceTest` is flaky. Could you rerun the Travis CI test, please?

**Comment by kramasamy** [comment]
@windie - restarted. once it finishes successfully, we can merge it.

**Pull request merged**
