### PR TITLE
Adding resources missing when operating without internet access

### LINKED ISSUE #2509: Heron admin UI does not work in offline environment
React and a few other javascript libraries are being referenced from cloudera cdn which fails in an offline (no internet) environment.

[Cloudera reference in HTML template](https://github.com/twitter/heron/blob/bedb3adee18aa415c263c27d0d211467fbcbad41/heron/tools/ui/resources/templates/application.html#L18)

### PR DESCRIPTION
**Pull request by nicknezis**
Adding resources missing when operating without internet access. closes #2509

### CODE REVIEW

**Comment by cckellogg** [comment]
Thank you for the pull request. This one https://github.com/twitter/heron/pull/2513 does the same thing and came in first so we are planning on merging this. Will this one work for you?

**Comment by mjschmidt** [comment]
Hey this is a duplication of effort. Nick and I mad the same exact changes. So use either, right now it looks like nick's build is finished and mine is still building due to a type I realized I needed to fix. So either will work. Maybe now we should merge in Nick's now.

**Comment by mjschmidt** [comment]
@cckellogg

**Comment by nicknezis** [comment]
The issue I was fixed was resolved by another pull request. Closing this pull request.

**Pull request closed without merging**
