### PR TITLE
Remove special case CentOS build files

### PR DESCRIPTION
**Pull request by objmagic**
for CentOS 7 build and general clean-up and refactoring

An internal PR (D28289) has also been submitted.

### CODE REVIEW

**Comment by kramasamy** [comment]
@objmagic - have you tested the package for centos7 before removing these files?

**Comment by huijunw** [comment]
what were these 2 files originally for?

**Comment by objmagic** [comment]
@huijunw because of Bazel's own issue, we have to write a separate BUILD file for CentOS 5 (and cannot reuse the one for Mac). This issue does not happen on CentOS 7. Since we are migrating to CentOS 7, we can remove these two historical files.

**Comment by huijunw** [comment]
thanks @objmagic

**Pull request merged**
