### PR TITLE
Adding sleep to TestSpout to throttle down cpu usage

### PR DESCRIPTION
**Pull request by billonahill**
This issue came up in the forums:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/heron-users/xxFlKHCAUU4/5WFt8s0zAwAJ

It's annoying because it cranks the cpu, which is noisy and kills laptop batteries when not plugged in. :)

### CODE REVIEW

**Comment by objmagic** [comment]
sometimes we use it to benchmark in cluster so maybe we don't want to throttle it all the time?

**Comment by billonahill** [comment]
@objmagic it's easy to disable by using the default constructor. I recommend we create our benchmark topologies that way, but the tutorial topology we reference in the quickstart shouldn't drain the cpu.

**Comment by objmagic** [comment]
ok. lgtm

**Comment by nlu90** [comment]
@billonahill 

This integration test: "BasicTopologyOneTaskScaleUp" is flaky. I've seen it fails the internal CI several times. Any ideas about this test?

**Comment by billonahill** [comment]
Not yet, but I'm trying to reproduce. I hadn't seen this one in a while, so I thought it was ok...

**Comment by nlu90** [comment]
I also saw this test failed internally. If you like, I can share the failed build number and log with you

**Comment by billonahill** [comment]
Yeah, I saw that. I was also able to reproduce locally. I think there's a potential race condition with when the physical plan gets updated vs when the stream managers get restarted, but still investigating.

**Pull request merged**
