### PR TITLE
Improved content

### PR DESCRIPTION
**Pull request by SuriyaaKudoIsc**
@twitter

### CODE REVIEW

**Comment by kramasamy** [comment]
👍

**Comment by objmagic** [comment]
Please accept CLA first: https://engineering.twitter.com/opensource/cla

**Comment by lucperkins** [comment]
README is commonly used as a noun. I'm not sure that I really see the value of this change, personally.

**Comment by kramasamy** [comment]
@SuriyaaKudoIsc - closing since the recommendation is that README is a noun and there is no need for this change.

**Pull request closed without merging**
