### PR TITLE
Added the steps for debug java topologies

### PR DESCRIPTION
**Pull request by vidit-bhatia**

### CODE REVIEW

**Comment by kramasamy** [comment]
@lucperkins - can you review this PR please?

**Comment by lucperkins** [comment]
I've performed a significant re-write of this section. Please re-submit with these changes:

#### 7. Debugging Java topologies

The jar containing the code for building the topology, along with the spout and bolt 
code, is deployed in the containers. A Heron Instance is started in each container, with each
Heron Instance responsible for running a bolt or a spout. One way to debug Java code is to write debug logs to the log files for tracking and debugging purposes.

Logging is the preferred mode for debugging as it makes it easer to find issues in both the short and long term in the topology. If you want to perform step-by-step debugging of a JVM
process, however, this can be achieved by enabling remote debugging for the Heron Instance.

Follow these steps to enable remote debugging:

1. Add Java options to enable debugging on all the Heron Instances that will be started. This can be achieved by adding the options `"agentlib:jdwp=transport=dt_socket,address=8888,server=y,suspend=n"`. Here's an example:

  ```java
  conf.setDebug(true);
  conf.setMaxSpoutPending(10);
  conf.put(Config.TOPOLOGY_WORKER_CHILDOPTS, "-XX:+HeapDumpOnOutOfMemoryError");
  conf.setComponentJvmOptions("word",
      "-agentlib:jdwp=transport=dt_socket,address=8888,server=y,suspend=n");
  conf.setComponentJvmOptions("exclaim1",
       "-agentlib:jdwp=transport=dt_socket,address=8888,server=y,suspend=n");
  ```

2. Use the steps as given in the tutorial to [set up remote debugging in Eclipse](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-remotejava_launch_config.htm).

  To set up remote debugging with IntelliJ, see the [remote debugging instructions](https://www.jetbrains.com/help/idea/2016.2/run-debug-configuration-remote.html) .

3. Once the topology is activated, start the debugger at `localhost:{PORT}` if in standalone local deployment or `{IP}/{HOSTNAME}:{PORT}` for multi-container remote deployment, and you will then be able to debug the code step by step.

**Comment by kramasamy** [comment]
thanks @lucperkins - this looks excellent. @vidit-bhatia - please review and use the contents provided by @lucperkins

**Comment by kramasamy** [comment]
@vidit-bhatia - just wondering if you had a chance to take a look at this.

**Comment by vidit-bhatia** [comment]
@kramasamy @lucperkins looks good committing now

**Comment by kramasamy** [comment]
@vidit-bhatia - please update the pull request with the content of @lucperkins - then I can merge it.

**Comment by vidit-bhatia** [comment]
@kramasamy done

**Pull request merged**
