### PR TITLE
Add Bazel 0.3.0 support

### PR DESCRIPTION
**Pull request by windie**
This PRs adds Bazel 0.3.0 support.

Bazel 0.3.0 removes a lot of files from the Bazel binary in https://github.com/bazelbuild/bazel/commit/d91d047da35511487c4fcce6f5e438ba779a668b#diff-b6d6ae0d41e460758b3217d7fd82094c so we cannot use `@bazel_tools//third_party/...` for `junit`, `mockito` and `joda` any more. This PR just adds them to WORKSPACE as maven_jars to makes the project support both Bazel 0.2.3 and 0.3.0.

### CODE REVIEW

**Comment by nlu90** [comment]
Please don't merge this PR until we verified this change also doesn't break Twitter's internal building environment for Heron.

**Comment by kramasamy** [comment]
@nlu90 - this PR works even with bazel 0.2.3 in my mac.

**Comment by windie** [comment]
Yes, this one works with both Bazel 0.2.3 and 0.3.0.

I was working on #524 and found Brew had upgraded to Bazel 0.3.0. So I submitted this PR to unblock #524.

**Comment by kramasamy** [comment]
👍

**Comment by kramasamy** [comment]
@windie - now you could work on #524

**Comment by maosongfu** [comment]
@kramasamy @nlu90 
Did we verify this change not to break Twitter's internal building environment for Heron?

**Comment by kramasamy** [comment]
@maosongfu - I verified with bazel 0.2.3 and it works. Essentially it works with both bazel 0.2.3 and bazel 0.3.0. In Twitter environment, we can continue to use bazel 0.2.3

**Pull request merged**
