### PR TITLE
Clean up for the compiling docs

### PR DESCRIPTION
**Pull request by lucperkins**
There are *no* significant content changes in this PR, but I think that these pages are going to behavily trafficked so I wanted to be sure that they look nice and tidy, have proper code highlighting, etc.

### CODE REVIEW

**Comment by kramasamy** [comment]
@lucperkins - is this still needed?

**Comment by objmagic** [comment]
This looks good to me. I think we should merge it.

**Comment by taishi8117** [comment]
Should we merge this?

**Comment by kramasamy** [comment]
Let us wait until what @lucperkins says.

**Comment by lucperkins** [comment]
@kramasamy @taishi8117 @objmagic Yes, these changes are still valid. Please merge if the changes look okay.

**Pull request merged**
